<script setup>
// utils
import { ref } from 'vue'

// state manager
import { request } from '../stateStore.js'

// reuseable components
import FormInput from '../components/FormInput.vue'
import FormInputTrxIdGen from '../components/FormInputTrxIdGen.vue'

// local vars
const endPoint = ref(
  'https://preprod.prtpg.com/transactionServices/REST/v1/payments'
)
</script>

<template>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Server-to-Server</h5>
      <h6 class="card-subtitle mb-2 text-muted fs-6">
        In a synchronous workflow, the payment data are directly sent to the
        server with initial payment request. That means that the transaction can
        be processed straight away.
      </h6>

      <hr />

      <FormInput
        input-id="endpoint"
        input-label="API Endpoint"
        input-placeholder="https://preprod.prtpg.com/transaction/Checkout"
        v-model="endPoint"
        helper-text-id="endpointHelper"
        helper-text="Change the subdomain to 'secure' for a live transaction."
      />

      <FormInput
        input-id="partnerId"
        input-label="Partner ID"
        input-placeholder="421"
        v-model="request.partnerId"
        helper-text-id="partnerIdHelper"
        helper-text="The Partner's unique ID, this is assigned by the gateway provider."
      />

      <FormInput
        input-id="username"
        input-label="Merchant Username"
        input-placeholder="421"
        v-model="request.username"
        helper-text-id="usernameHelper"
        helper-text="This is assigned by the gateway provider."
      />

      <FormInput
        input-id="secureKey"
        input-type="password"
        input-label="Merchant Secure Key"
        input-placeholder="XXXXXXXXX"
        v-model="request.secureKey"
      />

      <FormInput
        input-id="memberId"
        input-label="Member ID"
        input-placeholder="12598"
        v-model="request.memberId"
        helper-text-id="memberIdHelper"
        helper-text="Merchant's unique ID, this is assigned by the gateway provider."
      />

      <FormInputTrxIdGen
        input-id="merchantTransactionId"
        input-label="Merchant Transaction ID"
        input-placeholder="test_transaction_0001"
        v-model="request.merchantTransactionId"
        helper-text-id="merchantTransactionIdHelper"
        helper-text="This is auto-generated by the app on page-load. Click the 'New' button to generate a new one."
      />

      <FormInput
        input-id="amount"
        input-label="Amount"
        input-placeholder="1.00"
        v-model="request.amount"
      />

      <FormInput
        input-id="merchantRedirectUrl"
        input-label="Merchant Redirect URL"
        input-placeholder="https://prtpg.herokuapp.com/display_request_result.php"
        v-model="request.merchantRedirectUrl"
      />
    </div>
  </div>
</template>
