<script setup>
// utils
import { ref, onMounted } from 'vue'
import md5 from 'crypto-js/md5'
import { formatParams } from '../utils/stringFormatters.js'

// state manager
import { request } from '../stateStore.js'

// reuseable components
import FormInput from '../components/FormInput.vue'
import FormText from '../components/FormText.vue'
import FormInputTrxIdGen from '../components/FormInputTrxIdGen.vue'

// local vars
const endPoint = ref('https://preprod.prtpg.com/transaction/Checkout')
let parameters = ref('')
const defaultParameters = ref([
  'orderDescription=This is a test transaction.',
  'country=PH',
  'city=Makati',
  'state=NCR',
  'postcode=1227',
  'street=Valero',
  'telnocc=63',
  'phone=9854785236',
  'email=flex.gateway@payreto.com',
  'ip=192.168.0.1',
  'currency=REPLACE_ME',
  'terminalid=REPLACE_ME',
  'paymentMode=REPLACE_ME',
  'paymentBrand=REPLACE_ME',
])

/**
 * generate hash
 */
function generateHash() {
  // MEMBERID|TOTYPE|AMOUNT|TRANSACTIONID|REDIRECTURL|SECURE_KEY
  console.info(
    md5(
      `${request.memberId}|${request.totype}|${request.amount}|${request.merchantTransactionId}|${request.merchantRedirectUrl}|${request.secureKey}`
    ).toString()
  )
}

/**
 * mounted method here
 */
onMounted(() => {
  parameters.value = formatParams(defaultParameters.value, '\n')
})
</script>

<template>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Standard Checkout</h5>
      <h6 class="card-subtitle mb-2 text-muted fs-6">
        In a Standard Checkout, the merchant needs to POST the intial request to
        the Paymentz hosted checkout page where customer will provide
        card/account details. Once the payment is verified, the customer is
        redirected back to the <code>merchantRedirectUrl</code> along with the
        payment status.
      </h6>

      <hr />

      <FormInput
        input-id="endpoint"
        input-label="API Endpoint"
        input-placeholder="https://preprod.prtpg.com/transaction/Checkout"
        v-model="endPoint"
      />

      <FormInput
        input-id="memberId"
        input-label="Member ID"
        input-placeholder="12598"
        v-model="request.memberId"
        helper-text-id="memberIdHelper"
        helper-text="Merchant's unique ID, this is assigned by the gateway provider."
      />

      <FormInput
        input-id="totype"
        input-label="To Type"
        input-placeholder="PSP Name"
        v-model="request.totype"
        helper-text-id="totypeHelper"
        helper-text="Merchant's Partner/PSP name. Required to authenticate a transaction's request."
      />

      <FormInput
        input-id="amount"
        input-label="Amount"
        input-placeholder="1.00"
        v-model="request.amount"
      />

      <FormInputTrxIdGen
        input-id="merchantTransactionId"
        input-label="Merchant Transaction ID"
        input-placeholder="test_transaction_0001"
        v-model="request.merchantTransactionId"
        helper-text-id="merchantTransactionIdHelper"
        helper-text="This is auto-generated by the app on page-load. Click the 'New' button to generate a new one."
      />

      <FormInput
        input-id="merchantRedirectUrl"
        input-label="Merchant Redirect URL"
        input-placeholder="https://prtpg.herokuapp.com/display_request_result.php"
        v-model="request.merchantRedirectUrl"
      />

      <FormInput
        input-id="secureKey"
        input-type="password"
        input-label="Merchant Secure Key"
        input-placeholder="XXXXXXXXXXXXX"
        v-model="request.secureKey"
      />

      <FormText
        text-id="std-checkout-params"
        text-label="Parameters"
        :text-height="350"
        v-model="parameters"
      />
    </div>
  </div>
</template>
